# Generated by Django 4.2.13 on 2026-04-22 06:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('match_type', models.CharField(choices=[('1v1', '1v1'), ('2v2', '2v2')], default='2v2', max_length=3)),
                ('num_courts', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='sessions_app.session')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('session', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('total_wait_rounds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permanent_partner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_of', to='sessions_app.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='sessions_app.session')),
            ],
            options={
                'unique_together': {('session', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PlayerRoundHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_ids', models.JSONField(default=list)),
                ('opponent_ids', models.JSONField(default=list)),
                ('sat_out', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sessions_app.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sessions_app.round')),
            ],
            options={
                'unique_together': {('player', 'round')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('court_number', models.PositiveSmallIntegerField()),
                ('team1_players', models.JSONField()),
                ('team2_players', models.JSONField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sessions_app.round')),
            ],
            options={
                'ordering': ['court_number'],
                'unique_together': {('round', 'court_number')},
            },
        ),
    ]
