# Generated by Django 4.2.13 on 2026-04-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, choices=[('team1', 'team1'), ('team2', 'team2')], max_length=5, null=True),
        ),
    ]
