# Generated by Django 4.2.13 on 2026-05-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0003_session_generation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sit_out',
            field=models.BooleanField(default=False),
        ),
    ]
