# Generated by Django 4.2.13 on 2026-05-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0004_add_player_sit_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='sit_out',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
