# Generated by Django 4.2.13 on 2026-05-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0005_add_sit_out_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='removed_players',
            field=models.JSONField(default=dict),
        ),
    ]
