# Generated by Django 4.2.13 on 2026-05-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0006_add_session_removed_players'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['round', 'winner'], name='sessions_ap_round_i_3bfaf3_idx'),
        ),
    ]
