# Generated by Django 4.2.13 on 2026-05-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0009_push_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='sport_type',
            field=models.CharField(choices=[('pickleball', 'Pickleball'), ('tennis', 'Tennis'), ('badminton', 'Badminton'), ('ping_pong', 'Ping Pong'), ('padel', 'Padel'), ('others', 'Others')], default='pickleball', max_length=10),
        ),
    ]
