# Generated by Django 4.2.13 on 2026-05-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0011_push_subscription_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_mode',
            field=models.CharField(choices=[('rotation', 'Rotation'), ('tournament', 'Tournament')], default='rotation', max_length=10),
        ),
        migrations.AddField(
            model_name='session',
            name='tournament_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
